config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "welcome#index"

  get "/shelters", to: "shelters#index"
  get "/shelters/new", to: "shelters#new"
  get "/shelters/:id", to: "shelters#show"
  delete "/shelters/:id", to: "shelters#destroy"
  post "/shelters", to: "shelters#create"
  get "/shelters/:id/edit", to: "shelters#edit"
  patch "/shelters/:id", to: "shelters#update"


  get "/pets", to: "pets#index"
  get "/pets/:id", to: "pets#show", as: "pet_application"
  get "/pets/:id/edit", to: "pets#edit"
  patch "/pets/:id", to: "pets#update"
  delete "/pets/:id", to: "pets#destroy"

  get "/shelters/:shelter_id/pets", to: "shelter_pets#index"
  get "/shelters/:shelter_id/pets/new", to: "shelter_pets#new"
  post "/shelters/:shelter_id/pets", to: "shelter_pets#create"
  get "/shelters/:id/pets/:id", to: "pets#show"

  get "/applications", to: "applications#index"
  get "/applications/new", to: "applications#new"
  post "/applications", to: "applications#create"
  get "/applications/:id", to: "applications#show", as: "applications_show" #try to keep this at the bottom for now (fixed id = new)
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :pet_applications
  has_many :pets, through: :pet_applications

 validates_presence_of :name, :address, :city, :state, :zip, :description

 def new_status
   "In Progress"
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :shelter
  has_many :pet_applications
  has_many :applications, through: :pet_applications
  validates_presence_of :name, :description, :approximate_age, :sex

  validates :approximate_age, numericality: {
              greater_than_or_equal_to: 0
            }

  enum sex: [:female, :male]

  def self.search(pet_name)
    where("lower(name) like ?", "%#{pet_name.downcase}%") #used to be just (name: pet_name)
  end
end

app/models/pet_application.rb
class PetApplication < ApplicationRecord
  belongs_to :pet
  belongs_to :application
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @applications = Application.all
  end

  def show
    if params[:search_pets] && params[:id]
      @matching_pets = Pet.search(params[:search_pets])
      @application = Application.find(params[:id])
    elsif params[:want_pet] && params[:id]
      @pet_application = PetApplication.create!(pet_id: params[:want_pet],application_id: params[:id])
      @application = Application.find(params[:id])
    else
      @application = Application.find(params[:id])
    end
  end

  def new
    @application = Application.new
  end

  def create
    application = Application.new(application_params)
    if application.save
      redirect_to "/applications/#{application.id}"
      # if @pet_application
      #   # params[:pet_names] = [@pet_application.pet.name]
      #   # As the 'Adopt this pet' button is clicked, i must collect those names and add them to an array that will belong to the pet_names section of a newly created application that has not been submitted yet.
      # end
    else
      flash.now[:alert] = "Form must be completed in order to submit the application. Please complete every field in the form."
      render :new
    end
  end

  private
  def application_params
    params.permit(:name, :address, :city, :state, :zip, :description, :status)
  end
end

app/controllers/pet_applications_controller.rb
class PetApplicationsController < ApplicationController
  def index
    @pet_application = PetApplication.all
  end

  def new
    @pet_application = PetApplication.new
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    pet = Pet.find(params[:id])
    pet.update(pets_params)
    redirect_to "/pets/#{pet.id}"
  end

  def destroy
    Pet.destroy(params[:id])
    redirect_to '/pets'
  end

  private
  def pets_params
    params.permit(:image, :name, :description, :approximate_age, :sex, :adoptable)
  end

end

app/controllers/shelter_pets_controller.rb
class ShelterPetsController < ApplicationController

  def index
    @shelter = Shelter.find(params[:shelter_id])
  end

  def new
    @shelter = Shelter.find(params[:shelter_id])
  end

  def create
    @shelter = Shelter.find(params[:shelter_id])
    @shelter.pets.create(shelter_pets_params)
    redirect_to "/shelters/#{@shelter.id}/pets"
  end

  private
  def shelter_pets_params
    params.permit(:image, :name, :description, :approximate_age, :sex, :adoptable)
  end

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  def index
    @shelters = Shelter.all
  end

  def show
    @shelter = Shelter.find(params[:id])
  end

  def new
  end

  def create
    Shelter.create(shelter_params)
    redirect_to '/shelters'
  end

  def edit
    @shelter = Shelter.find(params[:id])
  end

  def update
    shelter = Shelter.find(params[:id])
    shelter.update(shelter_params)
    redirect_to "/shelters/#{shelter.id}"
  end

  def destroy
    Shelter.destroy(params[:id])
    redirect_to '/shelters'
  end

  private
  def shelter_params
    params.permit(:name, :address, :city, :state, :zip)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # code
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_form.html.erb
<%= form_with url: "/applications", local: true, method: :post do |form| %>
  <%= form.label :name %>
  <%= form.text_field(:name, size:30) %><br>

  <%= form.label :address %>
  <%= form.text_field(:address, size:25) %>

  <%= form.label :city %>
  <%= form.text_field :city %>

  <%= form.label :state %>
  <%= form.text_field :state %>

  <%= form.label :zip %>
  <%= form.number_field :zip %><br>

  <%= form.label "why do you want to adopt?" %><br>
  <%= form.text_area(:description, size: "60x10") %><br>

  <%= form.submit "Submit" %>
<% end %>

app/views/applications/index.html.erb
<p>This is the index page for applications page</p><br>
<p>... unsure if it will be needed for the issues I am having, so experimenting.</p>

app/views/applications/new.html.erb
<h2>Start a New Application</h2>
<%= render "form" %>

app/views/applications/show.html.erb
<h3>Here is the information you've provided</h3>
  <p>NAME: <%= @application.name %></p>
  <p>STREET ADDRESS: <%= @application.address %></p>
  <p>CITY: <%= @application.city %></p>
  <p>STATE: <%= @application.state %></p>
  <p>ZIP: <%= @application.zip %></p>
  <p>WHY DO YOU WANT TO ADOPT?<br>
    <%= @application.description %></p>
  <p>YOUR APPLICATION STATUS: <%= @application.new_status %></p>

  <section>
    <% if @pet_application %>
    <p>PETS ADDED TO YOUR APPLICATION:</p>
      <% @application.pets.each do |pet| %>
          <%= link_to "#{pet.name}", pet_application_path(pet.id) %>
      <% end %><br>
      <h3><%= link_to "submit application", "/applications/#{@application.id}" %></h3>
    <% end %>
  </section>

  <section>
    <h2>Add a Pet to this Application</h2>
    <%= form_with url: "/applications/#{@application.id}", local: true, method: :get do |form| %>
      <%= form.label "search pets by name:" %>
      <%= form.search_field :search_pets %>
      <%= form.submit "search" %>
    <% end %>
  </section>

  <% if @matching_pets %>
      <section>
        <% @matching_pets.each do |pet| %>
          Name: <%= pet.name %> <%= link_to "adopt this pet!", applications_show_path(want_pet: pet.id) %><br>
        <% end  %>
      </section>
    <% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoptDontShopM2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  <header>
    <div class="nav-bar">
      <ul>
        <p><%= link_to "Back to Home", "/" %>
          <%= link_to "Go to Shelters", "/shelters" %>
          <%= link_to 'Go to Pets', "/pets" %>
  </head><br>

  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<%= form_tag "/pets/#{@pet.id}", method: :patch do %>
  <h2>Edit <%= link_to "#{@pet.name}", "/pets/#{@pet.id}" %></h2>
  <%= label_tag :image %>
  <%= text_field_tag :image, @pet.image %><br>
  <%= label_tag :name %>
  <%= text_field_tag :name, @pet.name %><br>
  <%= label_tag :description %>
  <%= text_field_tag :description, @pet.description %><br>
  <%= label_tag :approximate_age %>
  <%= text_field_tag :approximate_age, @pet.approximate_age %><br>
  <%= label_tag :sex %>
  <%= text_field_tag :sex, @pet.sex %><br>
  <%= submit_tag "Update Pet" %>
<% end %>

app/views/pets/index.html.erb
<h1>All Pets</h1>

<%= link_to "Start an Application", "/applications/new" %><br>

<% @pets.each do |pet| %>
  <% if pet.adoptable == true %>
  <section id="pet-<%=pet.id%>">
      <h2>name: <%= link_to "#{pet.name}", "/pets/#{pet.id}" %></h2>
      <%= image_tag "#{pet.image}" %><br>
      approx age: <%= pet.approximate_age %><br>
      sex: <%= pet.sex%><br>
      shelter: <%= link_to "#{pet.shelter.name}", "shelters/#{pet.shelter.id}" %><br>
      <a href="/pets/<%= pet.id %>/edit">Update Pet</a>
      <%= link_to "Delete Pet", "/pets/#{pet.id}", method: :delete %><br>
    </section>
  <% end %>
<% end %>

app/views/pets/show.html.erb
<h2>Name: <%= "#{@pet.name}" %></h2>
<%= image_tag "#{@pet.image}" %><br>
Description: <%= @pet.description %><br>
Approx Age: <%= @pet.approximate_age %><br>
Sex: <%= @pet.sex %><br>
Adoption Status: <%= @pet.adoptable? %><br>
<a href="/pets/<%= @pet.id %>/edit">Update Pet</a>
<%= button_to "Delete Pet", "/pets/#{@pet.id}", method: :delete %>

app/views/shelter_pets/index.html.erb
<h1><%= link_to "#{@shelter.name}", "/shelters/#{@shelter.id}" %>'s Pets</h1>
<%= link_to "Add Pet", "/shelters/#{@shelter.id}/pets/new" %><br>
<% @shelter.pets.each do |pet| %>
<h2>Name:<%= link_to "#{pet.name}", "pets/#{pet.id}" %></h2>
  <%= image_tag "#{pet.image}" %><br>
  Approx Age:<%= pet.approximate_age %><br>
  Sex:<%= pet.sex %><br>
<% end %>

app/views/shelter_pets/new.html.erb
<%= form_tag "/shelters/#{@shelter.id}/pets" do %>
  <h2>Create a New Pet</h2>
  <%= label_tag :image%>
  <%= text_field_tag :image %><br>
  <%= label_tag :name %>
  <%= text_field_tag :name %><br>
  <%= label_tag :description%>
  <%= text_field_tag :description %><br>
  <%= label_tag :approximate_age %>
  <%= text_field_tag :approximate_age %><br>
  <%= label_tag :sex %>
  <%= text_field_tag :sex%><br>
  <%= submit_tag 'Create Pet' %>
<% end %>

app/views/shelters/edit.html.erb
<%= form_tag "/shelters/#{@shelter.id}", method: :patch do %>
  <h2>Edit <%= link_to "#{@shelter.name}", "shelters/#{@shelter.name}" %></h2>
  <%= label_tag :name %>
  <%= text_field_tag :name, @shelter.name %><br>
  <%= label_tag :address %>
  <%= text_field_tag :address, @shelter.address %><br>
  <%= label_tag :city %>
  <%= text_field_tag :city, @shelter.city %><br>
  <%= label_tag :state %>
  <%= text_field_tag :state, @shelter.state %><br>
  <%= label_tag :zip %>
  <%= text_field_tag :zip, @shelter.zip %><br>
  <%= submit_tag "Update Shelter" %>
<% end %>

app/views/shelters/index.html.erb
<h1>Shelters</h1>
<%= link_to 'New Shelter', '/shelters/new' %>
<% @shelters.each do |shelter| %>
  <section id="shelter-<%=shelter.id%>">
    <h2><%= link_to "#{shelter.name}", "shelters/#{shelter.id}" %></h2>
    <a href="/shelters/<%= shelter.id %>/edit">Edit Shelter</a>
    <%= link_to "Delete Shelter", "/shelters/#{shelter.id}", method: :delete %>
  </section>
<% end %>

app/views/shelters/new.html.erb
<%= form_tag '/shelters' do %>
  <h2>Create a New Shelter</h2>
  <%= label_tag :name %>
  <%= text_field_tag :name %><br>
  <%= label_tag :address %>
  <%= text_field_tag :address %><br>
  <%= label_tag :city %>
  <%= text_field_tag :city %><br>
  <%= label_tag :state %>
  <%= text_field_tag :state %><br>
  <%= label_tag :zip %>
  <%= text_field_tag :zip%><br>
  <%= submit_tag 'Create Shelter' %>
<% end %>

app/views/shelters/show.html.erb
<h2><%= @shelter.name %></h2>
<%= @shelter.address %>
<%= @shelter.city %>
<%= @shelter.state %>
<%= @shelter.zip %><br>
<%= link_to "#{@shelter.name}'s Pets", "/shelters/#{@shelter.id}/pets" %>
<a href="/shelters/<%= @shelter.id %>/edit">Edit Shelter</a>
<%= button_to "Delete Shelter", "/shelters/#{@shelter.id}", method: :delete %>

app/views/welcome/index.html.erb
<h1>Welcome to Adopt Don't Shop</h1>